version: '3'

services:
  dnbbot-api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    command: [ "sh", "-c", "/dnbbotapi/bin/api" ]
    restart: always
  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
