version: 2.1

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.21.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  #      - run:
  #          name: Run tests
  #          command: |
  #            mkdir -p /tmp/test-reports
  #            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
  #      - store_test_results:
  #          path: /tmp/test-reports
  build-docker-image:
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build --build-arg DNBBOT_MONGO_CONN_STR=${DNBBOT_MONGO_CONN_STR} --build-arg DNBBOT_ENV=prod --build-arg DNBBOT_API_VERSION=v1.0.${CIRCLE_BUILD_NUM} -t dnbbot .
            docker image tag dnbbot dnbbot.azurecr.io/dnbbot:v1.0.${CIRCLE_BUILD_NUM}
            docker image tag dnbbot dnbbot.azurecr.io/dnbbot:latest
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} dnbbot.azurecr.io
            docker push --all-tags dnbbot.azurecr.io/dnbbot

workflows:
  build-deploy-azure:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
