# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    working_directory: ~/repo
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/go:1.21.4
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  #      - run:
  #          name: Run tests
  #          command: |
  #            mkdir -p /tmp/test-reports
  #            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
  #      - store_test_results:
  #          path: /tmp/test-reports
  build-docker-image:
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build --build-arg DNBBOT_MONGO_PASS=${DNBBOT_MONGO_PASS} --build-arg DNBBOT_ENV=prod -t dnbbot .
            docker image tag dnbbot dnbbot.azurecr.io/dnbbot:v1.0.${CIRCLE_BUILD_NUM}
            docker image tag dnbbot dnbbot.azurecr.io/dnbbot:latest
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} dnbbot.azurecr.io
            docker push --all-tags dnbbot.azurecr.io/dnbbot

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test
